/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeInterface */

#ifndef _Included_NativeInterface
#define _Included_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeInterface
 * Method:    methodExit
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;[Ljava/lang/Object;Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_NativeInterface_methodExit
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring, jobject, jobjectArray, jobject);

/*
 * Class:     NativeInterface
 * Method:    methodEnter
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;[Ljava/lang/Object;Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_NativeInterface_methodEnter
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject, jobjectArray, jobject);

/*
 * Class:     NativeInterface
 * Method:    newObj
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_NativeInterface_newObj
  (JNIEnv *, jclass, jstring, jobject, jstring, jobject, jobject);

/*
 * Class:     NativeInterface
 * Method:    storeField
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_NativeInterface_storeField
  (JNIEnv *, jclass, jobject, jobject, jobject, jstring, jstring, jstring, jstring, jobject, jobject);

/*
 * Class:     NativeInterface
 * Method:    loadField
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_NativeInterface_loadField
  (JNIEnv *, jclass, jobject, jobject, jstring, jstring, jstring, jstring, jobject, jobject);

/*
 * Class:     NativeInterface
 * Method:    storeVar
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_NativeInterface_storeVar
  (JNIEnv *, jclass, jobject, jobject, jstring, jstring, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
